### ISSUE TITLE
Error Minified React error when trying to load installed addons

### ISSUE THREAD

**Issue by helloyanis** [ReGuilded/ReGuilded#52]
```js
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Os (https://www.guilded.gg/d3b4a19b/bundle.js:1:4907558)
    at p (https://www.guilded.gg/d3b4a19b/bundle.js:1:4850839)
    at h (https://www.guilded.gg/d3b4a19b/bundle.js:1:4852109)
    at https://www.guilded.gg/d3b4a19b/bundle.js:1:4854186
    at Ai (https://www.guilded.gg/d3b4a19b/bundle.js:1:4863656)
    at gl (https://www.guilded.gg/d3b4a19b/bundle.js:1:4903928)
    at ds (https://www.guilded.gg/d3b4a19b/bundle.js:1:4894465)
    at ls (https://www.guilded.gg/d3b4a19b/bundle.js:1:4894390)
    at Zl (https://www.guilded.gg/d3b4a19b/bundle.js:1:4891471)
    at https://www.guilded.gg/d3b4a19b/bundle.js:1:4843198
    at t.unstable_runWithPriority (https://www.guilded.gg/d3b4a19b/bundle.js:1:4917815)
    at Vo (https://www.guilded.gg/d3b4a19b/bundle.js:1:4842907)
    at qo (https://www.guilded.gg/d3b4a19b/bundle.js:1:4843143)
    at Ho (https://www.guilded.gg/d3b4a19b/bundle.js:1:4843078)
    at ae (https://www.guilded.gg/d3b4a19b/bundle.js:1:4912079)
    at Jt (https://www.guilded.gg/d3b4a19b/bundle.js:1:4820599)
    at HTMLDocument.r (https://www.guilded.gg/d3b4a19b/bundle.js:1:8694529)
```
![image](https://github.com/ReGuilded/ReGuilded/assets/40769776/d353ade6-a8b5-40f9-8c7e-a020180c7716)

**Comment by ItzNxthaniel** [comment]
Still investigating. The file that concerns this is quite new to me, requested help from @IdkGoodName as well. :)

**Comment by IdkGoodName** [comment]
Should be solved.
